exclude: "\\.idea|test/remote-cases/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
            - types-PyYAML
            - types-attrs
            - types-paramiko
            - types-pkg_resources
            - types-python-dateutil
            - types-requests
            - types-toml

  # TODO: re-enable this!
  #    - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #      rev: 2.1.5
  #      hooks:
  #        - id: shellcheck
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: make test
        language: system
        types_or: [ python, shell ]
        pass_filenames: false
        require_serial: true
