name: Ensure pre-commit hooks have been run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure virtualenv set up for pylint
        run: make ce
      - name: Run all pre-commit hooks (except python tests)
        run: env SKIP=test .poetry/bin/poetry run pre-commit run --all
